name: Run Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: "Run Tests"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt && pip install -e .

      - name: Run tests
        run: pytest
